### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by SafaAlfulaij** [kafeg/qtrest#1]
Hello!
Sorry for this silly question, but can this be used for a website that has different API methods?
If yes, can you please just guide me some steps? Because I'm a bit new to C++ (Blame me) and need to know just some basic information about this :)

Thanks!

**Comment by kafeg** [comment]
Hi! Yes, you may to implement some API-classes and use them from different models or by direct.

Did you see example application code? Link: https://github.com/kafeg/qtrest-example

**Comment by SafaAlfulaij** [comment]
I think I missed that example 😔
Thanks a lot! 👌

**Comment by SafaAlfulaij** [comment]
I started hacking today and it's going nice :)

One problem is that I'm unable to use the basic HTTP auth method, which uses username and password.
I tried thses, but none of them worked for me:
```
authTokenHeader: "Authorization"
authToken: "username password"
-----
authTokenHeader: "Basic"
authToken: "password"
-----
authTokenHeader: "username"
authToken: "password"
```
Maybe something is wrong with the website, but I want to be sure what is the right way to use it!

Thanks a lot! Really nice library. :clap:

**Comment by kafeg** [comment]
Hi! Library not supported user/pass authorization by authTokenHeader/authToken
If you send username|password via headers, you must to override method
virtual QNetworkRequest createRequest(const QUrl &url) const;

If you send username/password in request body, you must set them in each request in your API class.

**Comment by SafaAlfulaij** [comment]
Yes! Thanks that worked! :)
Now a question, if I have a request that gets an object instead of a list, it it possible to parse it with any method right now? All what I found are lists :)
I found the implementation of `getCouponDetail`, but it seems it's not used.

An example of returned JSON:
```
{
    "YML_KEY": {
        "mimetype": "text/plain",
        "file-extensions": ".yml, .yaml",
        "description": "YAML Files based on the content"
    },
    "PHP_INI_KEY": {
        "mimetype": "text/plain",
        "file-extensions": ".ini",
        "description": "PHP INI Files based on content"
    },
    "XLIFF": {
        "mimetype": "text/xml",
        "file-extensions": ".xlf, .xliff, .xml",
        "description": "XLIFF file"
    },
    ...
}
```

**Comment by kafeg** [comment]
Hi! Please see to function QVariantList AbstractJsonRestListModel::getVariantList(QByteArray bytes) in file src/models/abstractjsonrestlistmodel.cpp

You may use QVariantList and QVariant for get subarray data by QVariant::toJsonArray() / toJsonDocument() / toJsonObject() / toJsonValue().

In QML it's doing automatically, as i test it a year ago)
