### ISSUE TITLE
Support for custom SSL configuration

### ISSUE THREAD

**Issue by estan** [kafeg/qtrest#2]
This looks like a very promising library. I would like to use it for communicating with our company private Buildbot using its REST API. The problem is that our Buildbot instance is proxied behind Apache, which is configured to do client certificate authentication (all employees have their own client certificate).

So I would need a way to configure the QSslConfiguration that qtrest uses, so that in my application, I can let the user select his/her `.p12` certificate bundle to be used for authentication.

**Comment by kafeg** [comment]
Hello. At now you may to use it by defaultSslConfiguration. Is it normal?

**Comment by estan** [comment]
That would work if I only had to communicate with one Buildbot instance. But the tools I'm planning to make should have the ability to communicate with several instances at the same time. For that, I would need to be able to specify the QSslConfiguration to use for each connection separately.

**Comment by kafeg** [comment]
You need hook function for doing some manipulations with QNetworkRequest before send this request to server, right? E.g. - set ssl configuration for request?

**Comment by estan** [comment]
Yes I think that should work (haven't written any code yet, just exploring options).

How about a virtual protected function in `APIBase` like

```cpp
QNetworkRequest APIBase::createRequest(const QUrl &url) const {
    return QNetworkRequest(url);
}
```

and change the `get`, `post`, `put`, `deleteResource`, `head`, `options` and `patch` functions to do

```cpp
    QNetworkRequest request = createRequest(url);
```

instead of

```cpp
    QNetworkRequest request = QNetworkRequest(url);
```

?

Then I could override `createRequest` in `MyAPI` with e.g:

```cpp
QNetworkRequest MyAPI::createRequest(const QUrl &url) const {
    QNetworkRequest request = QNetworkRequest(url);
    request.setSslConfiguration(...);
    return request;
}
```

**Comment by kafeg** [comment]
Yes, i think it's good solution. May you create pull request? Now I have no way to add the code =(
