### ISSUE TITLE
Using models with C++ 

### ISSUE THREAD

**Issue by cloud-rocket** [kafeg/qtrest#6]
Thanks for missing part in QT!
Can you provide some code snippets of how to use your lib in C++?
I have a little trouble using ready model (JsonRestListModel) from within C++:

I tried the following code:
```
    APIBase * api = new APIBase();

    api->setBaseUrl("http://192.168.2.200:8888");

    JsonRestListModel model;

    model.setApiInstance(api);

    model.requests()->setGet("/api/object");
    model.requests()->setGetDetails("/api/object/{id}");

    QVariantMap filters;
    filters["isArchive"] = "0";
    model.setFilters(filters);

    QStringList fields;
    fields << "id" << "name" << "type";
    model.setFields(fields);

    model.fetchDetail("object_id");
```
But it returns "No item with id object_id"

When inheriting from APIBase, the following code works:
```
    MyApi * client = new MyApi();

    client->setBaseUrl("http://192.168.2.200:8888");

    QNetworkReply *reply = client->getObjectDetails("object_id");

    QEventLoop loop;
    connect(reply, SIGNAL(finished()), &loop, SLOT(quit()));
    loop.exec();

    QVERIFY(!reply->error());

    QJsonParseError parseError;
    QJsonDocument document = QJsonDocument::fromJson(reply->readAll(), &parseError);

```

MyApi looks like the following:

```
QNetworkReply *MyApi::getObjectDetails(QString id)
{
    if (id.isEmpty()) {
        qDebug() << "ID is empty!";
        return 0;
    }

    QUrl url = QUrl(baseUrl()+"/api/object/"+id);

    QNetworkReply *reply = get(url);

    return reply;
}
```
Tanx!

**Comment by kafeg** [comment]
Hi!

Function 

`void BaseRestListModel::fetchDetail(QString id)`

works only with already cached data.

E.g. in your list model loaded 1000 items. 0-999 items may be load details, but 1000+ not.

Yoe are right, for 1 item, need to use Api class directly. List models must be used with QListView or other *view classes, or you may call `fetchMore` for load all needs items to model and than load details info for them.

**Comment by cloud-rocket** [comment]
Thanks!

Can you post an example of how to use CustomModel from within C++? 
(We miss the whole point of representing Rest objects as objects if we use API directly)

I did tried to to add MyApi (derivative of APIBase) to JsonRestListModel and call "reload" afterwards - it does  seem to load something, but how to access the properties properly?

**Comment by kafeg** [comment]
Did you see example project? https://github.com/kafeg/qtrest-example

Files you needed api/models/couponmodel.h and api/models/couponmodel.cpp

**Comment by cloud-rocket** [comment]
Yep, I seen how to implement a model, just asking how to use it properly  from within C++

**Comment by kafeg** [comment]
Use it as standard Qt models: 
- http://doc.qt.io/qt-5/model-view-programming.html
- http://doc.qt.io/qt-5/modelview.html
