### ISSUE TITLE
Using getVariantMap in C++ models

### ISSUE THREAD

**Issue by ReNoM** [kafeg/qtrest#7]
Why getVariantMap method is private in AbstractJsonRestListModel and AbstractXmlRestListModel? I think this method should be declared as protected similarly to getVariantList. The reason is that it can be useful for additional methods in C++ model. For example, calling an additional action of rest api.

**Comment by kafeg** [comment]
Hello!
If you realy need this, please make simple pull request, i will merge it.

Now I can not edit and run tests myself.

**Comment by ReNoM** [comment]
PR is already there. Thanks!

**Comment by kafeg** [comment]
Merged!
